services:
  nginx:
    image: bybatkhuu/nginx:3.3.3-260829
    build:
      context: .
    restart: always
    environment:
      - TERM=${TERM:-xterm}
      - TZ=${TZ:-UTC}
    volumes:
      - "./volumes/configs/nginx/templates:/etc/nginx/templates"
      - "./volumes/configs/nginx/sites-enabled:/etc/nginx/sites-enabled"
      - "./volumes/storage/nginx/logs:/var/log/nginx"
      - "./volumes/storage/nginx/www:/var/www"
    network_mode: host
    tty: true
